apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client-api
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: client-api
  template: 
    metadata:
      labels:
        app: client-api
    spec: 
      containers:
      - name: client
        image: client:latest
        imagePullPolicy: Never
        ports: 
        - containerPort: 3000
  
---

apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client-api
  ports:
    - port: 3000
      targetPort: 3000