apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user-api
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: user-api
  template: 
    metadata:
      labels:
        app: user-api
    spec: 
      containers:
      - name: user
        image: user:latest
        imagePullPolicy: Never
        ports: 
        - containerPort: 3002
  
---

apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-api
  ports:
    - port: 3002
      targetPort: 3002